version: '3'

services:
  web:
    container_name: carlosvilas.dev
    image: carlosvilasdev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
      - 12000:9229
    volumes:
      - ./:/usr/src/app/
